name: fetch-latest-data-and-deploy
on: [push]
jobs: 
  fetchandbuild:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14.x"
        - run: yarn
        - run: node scripts/getdata.js
        - run: yarn build
        - run: tar -h -C dist/ -cvf artifact.tar ./
        - uses: actions/upload-artifact@main
          with:
            name: github-pages
            path: ./artifact.tar
            if-no-files-found: warn
        - uses: actions/deploy-pages@v1-beta
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            timeout: 600000
            error_count: 10
            reporting_interval: 1000
